### ISSUE TITLE
TODO for ismir2018 tutorial prep

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/shablona#1]
- [ ] make a web page
  - [ ] with instructions for installing everything
- [ ] rename and rearrange module
- [ ] implement some broken tests
- [ ] configure travis, rtd

**Comment by tkell** [comment]
Webpage!  
https://bmcfee.github.io/shablona/
